name: Übung1

on:
  push:
  workflow_dispatch:
    inputs:
      starten:
        description: "Du hast den Knopf gedrückt"
        required: true
        #default: "Welt"    


jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Immer
        run: echo "${{ github.event_name }}"    
      - name: Nur bei Push
        run: echo "${{ github.ref_name }}"      
      - name: Wer hat den Knopf gedrückt
        run: echo "${{ inputs.name }}!"      