name: Übung3

on:
  push:
  workflow_dispatch:

jobs:
  Checkout:
    runs-on: ubuntu-latest  
    steps:
      - name: Muss fehlschlagen    
        continue-on-error: true
        run: cat hallo.txt     
      - name: Repository auschecken
        uses: actions/checkout           
      - name: Muss laufen        
        run: cat hello.txt