name: Übung3

on:
  push:
  workflow_dispatch:

jobs:
  Checkout:
    runs-on: ubuntu-latest  
    steps:
      - name: Muss fehlschlagen    
        run: cat hallo.txt
        continue-on-error: true
      - name: Muss laufen        
        uses: actions/checkout
        run: cat hello.txt