name: Übung2

on:
  push:
  workflow_dispatch:


jobs:
  vorbereiten:
    runs-on: ubuntu-latest  
    steps:
      - name: Begrüßung
        run: echo "Moin Moin!"       
  arbeiten:
    runs-on: ubuntu-latest
    needs: vorbereiten
    steps:
      - name: Zweite Meldung
        run: echo "Meldung Nummer 2!" 